### PR TITLE
Updated to use signals and added "advance" command.

### PR DESCRIPTION
**Pull request by nagledb**
These changes update piPass to use signals rather than the flag file. They also add a new "advance" command for advancing to the next zone.

I don't think the flag file was an issue, but since I was adding the signal support for advancing I thought it made sense to apply it to settings refreshing as well. I doubt the reduced I/O will make a meaningful difference on the lifespan of an SD card, but it does have the perk of immediately picking up changes to the Cycle Time.

The "advance" feature allows me to keep my Cycle time at a reasonably high level while still allowing me to manually advance as needed when I'm actively trying to play Mii Plaza or other games and get lots of Street Passes through.

### CODE REVIEW

**Comment by Matthew-Hsu** [comment]
I'm reviewing your changes and so far I really like what I see. The advance feature is quite nice and I really think the usage of signals is great. I will merge these changes in soon.

Thanks for contributing towards this project. I'll make sure to give you credit as well.

**Comment by Matthew-Hsu** [comment]
Manually merged changes with master to resolve conflicts.

**Comment by nagledb** [comment]
I'm glad to be able to contribute. :)

I just noticed that I missed including the "Advance" link in the menu bar when visiting pages outside of the "PiPass" submenu. I'll submit another pull request later today with changes to fix that.

**Comment by nagledb** [comment]
Ah, I see you already caught that I missed it and fixed it in the merge commit. Excellent.

**Pull request closed without merging**
